apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: metrics-egress
    tailscale.com/tailnet-fqdn: "$METRICS_FQDN"
  name: metrics-egress 
  namespace: monitoring
spec:
  ports:
    - port: 9402
      protocol: TCP
      targetPort: 9402
  externalName: unused 
  type: ExternalName
