apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: sandbox 
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ghcr.io/rhealitycheck/hello:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: metrics
            containerPort: 9402
          - name: app
            containerPort: 443
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: ts-auth
              key: TS_AUTHKEY
---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: sandbox 
  annotations:
     tailscale.com/hostname: app-metrics
spec:
  ports:
  - port: 9402
    protocol: TCP
    targetPort: 9402
  selector:
    app: app
  type: LoadBalancer
  loadBalancerClass: tailscale
