# ScrapeConfig is how Services of type external name can be scraped
# https://github.com/prometheus-operator/prometheus-operator/issues/218
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  labels:
    metricssource: hello
    cluster: app 
    prometheus: k8s
  name: hello-app
  namespace: monitoring
spec:
  scrapeInterval: 5s
  staticConfigs:
  - targets:
    - hello-metrics-egress.monitoring.svc:9402
