apiVersion: v1
kind: Namespace
metadata:
  name: hello
---
kind: Service
apiVersion: v1
metadata:
  name: hello 
  namespace: hello
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "hello"
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: docker-registry-registry-service:5000/hello:latest
        ports:
          - containerPort: 443
