apiVersion: v1
kind: Namespace
metadata:
  name: hello
---
kind: Service
apiVersion: v1
metadata:
  name: hello 
  namespace: hello
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9402"
        prometheus.io/scrape: "true"
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: ghcr.io/rhealitycheck/hello:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 443
          - name: metrics
            containerPort: 9402
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: ts-auth
              key: TS_AUTHKEY
