apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: monitoring-hello-metrics-egress
    tailscale.com/tailnet-ip: 100.118.163.137 
  name: hello  
  namespace: monitoring
spec:
  ports:
    - port: 2112
      protocol: TCP
      targetPort: 9402
  externalName: unused 
  type: ExternalName
