apiVersion: v1
kind: Service
metadata:
  name: hello-metrics-ingress
  namespace: hello
  annotations:
     tailscale.com/hostname: hello-metrics-ingress
spec:
  ports:
  - port: 9402
    protocol: TCP
    targetPort: 9402
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: hello
    app.kubernetes.io/name: hello
  type: LoadBalancer
  loadBalancerClass: tailscale
