apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: monitoring-hello-metrics-egress
    tailscale.com/tailnet-ip: 100.65.18.158
  name: hello-metrics-egress  
  namespace: monitoring
spec:
  ports:
    - port: 9402
      protocol: TCP
      targetPort: 9402
  externalName: unused 
  type: ExternalName
