apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/hostname: monitoring-hello-metrics-egress
    tailscale.com/tailnet-ip: 100.116.26.152 
  name: hello  
  namespace: monitoring
spec:
  ports:
    - port: 9402
      protocol: TCP
      targetPort: 2112
  externalName: unused 
  type: ExternalName
